- .github/workflows/python-publish.yml
- .gitignore
Updating to publish package to PyPi.
> Python publish

- .github/workflows/docker-publish-dockerhub.yml
- .github/workflows/docker-publish-github.yml
- .gitignore
Pushing a workflow to publish model container to dockerhub.
> Dockerhub publish

- .github/workflows/documentation.yaml
- src/aws/osml/models/server_utils.py
*Description of changes:* Adding a workflow for publishing sphinx documentation. Also changed the host from "0.0.0.0" to "127.0.0.1" per the feedback from a security scan. 
> Add workflow for hosting sphinx documentation

- .github/workflows/documentation.yaml
- Dockerfile
- README.md
- environment.yml
- src/aws/osml/models/aircraft/app.py
Updating docker container to explicitly install cuda deps. Updating a few minor things elsewhere.
> Updating package to build with correct cuda drivers

- .github/workflows/documentation.yaml
- Dockerfile
- README.md
- environment.yml
- src/aws/osml/models/aircraft/app.py
* Update documentation.yaml
* Specifying exact version for peaceiris/actions-gh-pages in documentation workflow.
* Updating package to build with correct cuda drivers
---------
> Updating package to build with correct cuda drivers (#7)

- .github/workflows/documentation.yaml
- Dockerfile
- README.md
- environment-py311.yml
- environment.yml
- setup.cfg
- src/aws/osml/models/aircraft/app.py
- src/aws/osml/models/server_utils.py
- tox.ini
Fixing CUDA driver installation 
> Fixing CUDA Driver Installation

- src/aws/osml/models/aircraft/app.py
There were issues referencing temporary files in high-volume situations due to colliding pointers to it's name.
> hotfix: Fixing temp file cleanup

- .github/workflows/osml-models-publish.yml
- .github/workflows/python-publish.yml
**Description of changes:**
- https://github.com/aws-solutions-library-samples/osml-models/pull/26
> fix: publish python package 

- src/aws/osml/models/server_utils.py
Fixing a bug where we were adding a ``null`` value to the ``geom_imcoords`` field when none were requested.
> fix: fixing bug in server_utils.py

- setup.cfg
Bumping release version to v1.1.0
> release: v1.1.0

- src/aws/osml/models/aircraft/app.py
Updating the aircraft model to correctly return an empty geojson if not features were found.
> fix: fixing no detection aircraft model bug

- src/aws/osml/models/centerpoint/app.py
- src/aws/osml/models/flood/app.py
Making default flood model configuration not output masks - including segmentation flag to control that piece. Upping the flood model default volume to make the test more robust of an increased feature count scenario.
> fix: fixing model bugs

- .github/workflows/docker-publish-dockerhub.yml
- .github/workflows/docker-publish-github.yml
* Adjusting docker GitHub actions memory to fix broken workflows
> fix: adjusting docker GitHub actions memory

- setup.cfg
**Description of changes:**
- Update the version package to 1.1.1
> build: update version package to 1.1.1

- Dockerfile
This fixes a failing build when driving builds from source.
> fix: adding setuptools to image Dockerfile

- setup.cfg
- Version bump to v1.1.2
- fix: adding setuptools to image Dockerfile
> build: version bump to v1.1.2

- .github/workflows/docker-build.yml
- .github/workflows/docker-publish.yml
- conda/environment-py310.yml
- conda/environment.yml
- docker/Dockerfile
- environment-py310.yml
- environment.yml
- setup.cfg
- src/aws/osml/models/__init__.py
- src/aws/osml/models/aircraft/__init__.py
- src/aws/osml/models/aircraft/app.py
- src/aws/osml/models/centerpoint/__init__.py
- src/aws/osml/models/centerpoint/app.py
- src/aws/osml/models/flood/__init__.py
- src/aws/osml/models/flood/app.py
- src/aws/osml/models/server_utils.py
- test/aws/osml/models/aircraft/test_aircraft_model.py
- test/aws/osml/models/centerpoint/test_centerpoint_model.py
- test/aws/osml/models/flood/test_flood_model.py
- test/aws/osml/test_server_utils.py
- tox.ini
This PR introduces a custom CloudWatch logging handler (`SMLogger`) that dynamically retrieves the Docker container ID and sets it as the log stream name. This allows logs from each container to be routed to separate streams in AWS CloudWatch, providing greater traceability in containerized environments.
1. **Fixed Default Logging:**
- Fixed a bug where conda was capturing all the output from the system.
3. **JSON Log Format:**
- Each log message is sent to CloudWatch in JSON format, which includes the various telemetry.
5. **Updated Unit Tests:**
- Increased unit test coverage / verbosity by creating isolated unit tests for ``server_utils.py``
- Updated reST styled PyDoc comments throughout unit tests.
5. **ENABLE_FAULT_DETECTION:**
- Added new …
> feat: implement custom logging patterns

- docker/Dockerfile
-  The guidance repo was failing due to incorrect `COPY` path command.  
> fix: incorrect copy path in Dockerfile

- setup.cfg
> build: version update to v1.2.0

- scripts/ecr_push.sh
Make it easier to work in a different region without changing other default args. Create the ECR repo if it doesn't exist. Terminate script if no aws credentials. Fix tagging.
> refactor: create ecr if needed, rearrange args, and fix tagging

- .github/workflows/pypi.yml
- docker/Dockerfile
Updated the pypi workflow to publish packages.
> ci: update pypi workflow
